packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  lmdb: set this to true or false
  msgpackr-extract: set this to true or false
minimumReleaseAgeExclude:
  - '@supabase/auth-js@2.112.3'
  - '@supabase/functions-js@2.112.3'
  - '@supabase/postgrest-js@2.112.3'
  - '@supabase/realtime-js@2.112.3'
  - '@supabase/storage-js@2.112.3'
  - '@supabase/supabase-js@2.112.3'
