/**
 * Writes src/environments/environment.ts from the build environment.
 *
 * The Supabase URL and publishable key are public by design — they identify the
 * project and are protected by RLS, not by secrecy. They are still sourced from
 * env vars so a different project can be pointed at without a code change.
 */
import { writeFileSync, mkdirSync } from 'node:fs';

const env = {
  supabaseUrl: process.env.SUPABASE_URL ?? 'https://hvymtfuojhzagfnszoey.supabase.co',
  supabaseKey: process.env.SUPABASE_PUBLISHABLE_KEY ?? 'sb_publishable_c8zezP75jyeZtVlYs_wwxw_o1-SBCsE',
  apiBase: process.env.API_BASE_URL ?? 'http://localhost:3001',
};

mkdirSync('src/environments', { recursive: true });
writeFileSync(
  'src/environments/environment.ts',
  `// GENERATED by scripts/gen-env.mjs — do not edit.\nexport const environment = ${JSON.stringify(env, null, 2)} as const;\n`,
);
console.log(`[gen-env] api=${env.apiBase} supabase=${env.supabaseUrl}`);
