// GENERATED by scripts/gen-env.mjs — do not edit.
export const environment = {
  "supabaseUrl": "https://hvymtfuojhzagfnszoey.supabase.co",
  "supabaseKey": "sb_publishable_c8zezP75jyeZtVlYs_wwxw_o1-SBCsE",
  "apiBase": "https://landjourney-api.vercel.app"
} as const;
