/**
 * Builds the API into Vercel's Build Output API (v3).
 *
 * Why this rather than emitting into a root `api/` directory: Vercel discovers
 * `api/**` functions from the *source tree it clones*. Files generated during
 * the build are never registered, so a build that writes handlers into `api/`
 * produces a deployment with no functions at all — every route 404s. That is
 * survivable when the CLI uploads a working directory that already contains the
 * built files, and it is exactly why doing so was a trap: the deployment
 * depended on gitignored artifacts built on someone's laptop, and a clean clone
 * could not reproduce it.
 *
 * `.vercel/output` is the contract for "the build produces the functions", so
 * the same commit deploys identically from anywhere.
 *
 * Each handler is bundled to a self-contained ESM file — including the workspace
 * contracts package — so the deployed function has no runtime resolution to do.
 */
import { build } from 'esbuild';
import { cpSync, existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

const SRC = 'apps/api/api';
const OUT = '.vercel/output';
const FUNCTIONS = join(OUT, 'functions');
const STATIC = join(OUT, 'static');
const RUNTIME = 'nodejs22.x';

function entries(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) return entries(full);
    return full.endsWith('.ts') ? [full] : [];
  });
}

/** `requests/[id]/index.ts` -> `api/requests/[id]`; `my-file.ts` -> `api/my-file`. */
function routeFor(file) {
  const rel = relative(SRC, file).replace(/\.ts$/, '');
  const trimmed = rel.endsWith('/index') ? rel.slice(0, -'/index'.length) : rel;
  return `api/${trimmed}`;
}

/** Writes one `.func` directory: the bundle plus its runtime config. */
async function emitFunction(route, entryPoint, contents) {
  const dir = join(FUNCTIONS, `${route}.func`);
  mkdirSync(dir, { recursive: true });

  if (entryPoint) {
    await build({
      entryPoints: [entryPoint],
      outfile: join(dir, 'index.js'),
      bundle: true,
      platform: 'node',
      target: 'node22',
      format: 'esm',
      packages: 'bundle',
      logLevel: 'warning',
    });
  } else {
    writeFileSync(join(dir, 'index.js'), contents);
  }

  writeFileSync(
    join(dir, '.vc-config.json'),
    JSON.stringify(
      {
        runtime: RUNTIME,
        handler: 'index.js',
        launcherType: 'Nodejs',
        // The handlers use res.status().json(), which the Node launcher supplies.
        shouldAddHelpers: true,
      },
      null,
      2,
    ),
  );

  // Each .func directory is its own deployment unit, so Node resolves the module
  // type from the nearest package.json to the handler — not from the repository
  // root. Without this the launcher parses an ESM bundle as CommonJS and every
  // invocation fails before reaching a single line of application code.
  writeFileSync(join(dir, 'package.json'), JSON.stringify({ type: 'module' }, null, 2));
  console.log(`[build-api] ${route}`);
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(FUNCTIONS, { recursive: true });
mkdirSync(STATIC, { recursive: true });

const files = entries(SRC);
if (files.length === 0) throw new Error(`No handlers found in ${SRC}`);

const routes = [];
for (const file of files) {
  const route = routeFor(file);
  await emitFunction(route, file);
  routes.push(route);
}

// Liveness probe with no dependencies, so a failure here means the runtime itself.
await emitFunction(
  'api/health',
  null,
  `// GENERATED by scripts/build-api.mjs
export default function handler(_req, res) {
  res.status(200).json({ ok: true, service: 'landjourney-api' });
}
`,
);
routes.push('api/health');

if (existsSync('apps/api/public')) {
  cpSync('apps/api/public', STATIC, { recursive: true });
}

/**
 * Static and exact-match routes resolve through the filesystem. Only the dynamic
 * ones need rewriting, to turn a path segment into the `id` query parameter the
 * handlers read.
 */
const dynamic = routes
  .filter((route) => route.includes('['))
  .sort((a, b) => b.length - a.length)
  .map((route) => {
    const params = [...route.matchAll(/\[([^\]]+)\]/g)].map((m) => m[1]);
    const src = `^/${route.replace(/\[[^\]]+\]/g, '([^/]+)')}$`;
    const query = params.map((p, i) => `${p}=$${i + 1}`).join('&');
    return { src, dest: `/${route}?${query}` };
  });

writeFileSync(
  join(OUT, 'config.json'),
  JSON.stringify({ version: 3, routes: [{ handle: 'filesystem' }, ...dynamic] }, null, 2),
);

console.log(`[build-api] ${routes.length} functions, ${dynamic.length} dynamic routes`);
