/**
 * Bundles each API handler into a self-contained ESM function under `api/`.
 *
 * Why bundle rather than let the platform trace imports: Vercel's Node builder
 * only compiles TypeScript that lives under the deployment root's `api/`
 * directory, and the Vercel CLI cannot set a project's Root Directory
 * non-interactively. Tracing therefore emitted imports pointing at `apps/api/**`
 * sources it never compiled, and every route failed with ERR_MODULE_NOT_FOUND.
 *
 * Bundling removes the question entirely — each output file has no imports left
 * to resolve — and keeps the real source in `apps/api` where it belongs.
 */
import { build } from 'esbuild';
import { mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

const SRC = 'apps/api/api';
const OUT = 'api';

function entries(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) return entries(full);
    return full.endsWith('.ts') ? [full] : [];
  });
}

const files = entries(SRC);
if (files.length === 0) throw new Error(`No handlers found in ${SRC}`);

for (const file of files) {
  const rel = relative(SRC, file).replace(/\.ts$/, '.js');
  const out = join(OUT, rel);
  mkdirSync(dirname(out), { recursive: true });
  await build({
    entryPoints: [file],
    outfile: out,
    bundle: true,
    platform: 'node',
    target: 'node22',
    format: 'esm',
    // Bundle everything, including the workspace contracts package, so the
    // deployed function has zero runtime resolution to do.
    packages: 'bundle',
    logLevel: 'warning',
  });
  console.log(`[build-api] ${file} -> ${out}`);
}

writeFileSync(
  join(OUT, 'health.js'),
  `// GENERATED by scripts/build-api.mjs
/** Liveness probe with no dependencies, so a failure here means the runtime itself. */
export default function handler(_req, res) {
  res.status(200).json({ ok: true, service: 'landjourney-api' });
}
`,
);
console.log(`[build-api] ${files.length + 1} functions built`);
